import { APP_CONFIG } from './running-score-config.js?v=11';
import { fetchWeather, reverseGeocode, searchLocations } from './weather.js?v=11';
import { fetchAirQuality } from './air-quality.js?v=12';
import { getStored, setStored, getCache, setCache } from './storage.js?v=11';
import { currentConditions, dailyScore, findBestRunningTimes, mergeHourly, rowsForDate, runnableRows, runningScoreDeductions, workoutScores } from './running-score.js?v=11';
import { coachMessage, environmentAlerts, gearAdvice, runNowMessage } from './running-coach.js?v=11';
import { fromPace, fromSpeed, paceTableRows, renderPace } from './pace-calculator.js';
import { renderHourlyChart } from './charts.js?v=12';
import { dateOnly, escapeHtml, formatValue, monthDay, parseClock, round, secondsToClock, timeOnly, weatherSymbol, weekday } from './utils.js';

const $ = id => document.getElementById(id);
const state = { location:getStored('location',APP_CONFIG.defaultLocation), selectedLocation:null, data:null, hourlyDay:0, hourlyKey:null, calcMode:'pace', controller:null, map:null, marker:null };

function setTheme(theme){document.documentElement.dataset.theme=theme;setStored('theme',theme);$('themeButton').setAttribute('aria-label',theme==='dark'?'라이트 모드 전환':'다크 모드 전환');}
setTheme(getStored('theme',matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));

function setLoading(isLoading){$('refreshButton').disabled=isLoading;$('refreshButton').textContent=isLoading?'…':'↻';}
function showError(message){$('errorBanner').textContent=message;$('errorBanner').hidden=!message;}
function nowSeoul(){return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());}
function updateClock(){$('headerClock').textContent=nowSeoul();const hourKey=currentSeoulHour();if(state.data&&state.hourlyKey!==hourKey)renderHourly();}
updateClock();setInterval(updateClock,1000);

async function loadData(force=false){
  state.controller?.abort();state.controller=new AbortController();setLoading(true);showError('');$('headerLocation').textContent=state.location.name;
  const cached=getCache(state.location);const fresh=cached && Date.now()-cached.savedAt<APP_CONFIG.cacheMinutes*60000;
  if(!force && fresh){state.data={...cached.payload,savedAt:cached.savedAt,fromCache:true};render();setLoading(false);return;}
  try{
    const [weatherResult,airResult]=await Promise.allSettled([fetchWeather(state.location,state.controller.signal),fetchAirQuality(state.location,state.controller.signal)]);
    if(weatherResult.status==='rejected') throw weatherResult.reason;
    const payload={weather:weatherResult.value,air:airResult.status==='fulfilled'?airResult.value:null,airError:airResult.status==='rejected'};
    setCache(state.location,payload);state.data={...payload,savedAt:Date.now(),fromCache:false};render();
    if(payload.airError) showError('날씨는 정상 표시 중이지만 대기질 데이터를 가져오지 못했습니다. 대기질 항목은 제외됩니다.');
  }catch(error){
    if(error.name==='AbortError')return;
    if(cached){state.data={...cached.payload,savedAt:cached.savedAt,fromCache:true};render();showError('새 데이터를 가져오지 못해 마지막 저장 데이터를 표시합니다.');}
    else showError(`날씨 데이터를 가져오지 못했습니다. 네트워크 연결을 확인해 주세요. (${error.message})`);
  }finally{setLoading(false);}
}

function render(){
  const {weather,air}=state.data;const hourly=mergeHourly(weather,air);const current=currentConditions(weather,hourly);const today=dateOnly(weather.current.time);const todayRows=rowsForDate(hourly,today);const futureTodayRows=todayRows.filter(row=>row.time>=weather.current.time);const tomorrow=weather.daily.time[1];const tomorrowRows=rowsForDate(hourly,tomorrow);const best=findBestRunningTimes(futureTodayRows);const futureBest=best[0];const todayScore=dailyScore(todayRows);const tomorrowScore=dailyScore(tomorrowRows);
  state.computed={hourly,current,today,todayRows,futureTodayRows,tomorrowRows,best,todayScore,tomorrowScore};
  renderHero(current,best,todayScore,futureBest);renderCurrent(current,weather);renderBest(best);renderHourly();renderComparison(todayScore,tomorrowScore,todayRows,tomorrowRows);renderCoach(current,futureBest);renderWeekly(weather,hourly);renderWorkouts(current);renderGear(current);
  $('updatedAt').textContent=`업데이트 ${new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit'}).format(new Date(state.data.savedAt))}${state.data.fromCache?' · 저장 데이터':''}`;
  const station=air?.current?.station_name;const measured=air?.current?.measured_at;
  $('observationSource').textContent=`기상청 관측${station?` · 에어코리아 ${station} 측정소${measured?` ${measured}`:''}`:' · 대기질 정보 없음'}`;
  $('offlineBanner').hidden=navigator.onLine;
}

function renderHero(c,best,todayScore,futureBest){const condition=scoreCondition(c.score),todayCondition=scoreCondition(todayScore);$('top').dataset.condition=condition.key;$('currentScore').classList.remove('skeleton-text');$('currentScore').textContent=c.score;$('currentGrade').textContent=condition.label;$('currentGrade').className=`grade-pill condition-${condition.key}`;$('runNowMessage').textContent=runNowMessage(c,futureBest);$('heroTemp').textContent=formatValue(c.temperature_2m,'°C',1);$('heroFeels').textContent=formatValue(c.apparent_temperature,'°C',1);$('heroHumidity').textContent=formatValue(c.relative_humidity_2m,'%',0);$('heroDew').textContent=formatValue(c.dew_point_2m,'°C',1);$('todayBestScore').textContent=best[0]?`${best[0].score}점`:'--점';$('todayBestTime').textContent=best[0]?`BEST TIME ${timeOnly(best[0].start)}–${endLabel(best[0])}`:'오늘 남은 추천 시간 없음';$('todayScore').textContent=todayScore??'--';$('todayGrade').textContent=todayCondition.label;$('todayGrade').className=`condition-text-${todayCondition.key}`;$('todaySummary').textContent=best[0]?`앞으로는 ${timeOnly(best[0].start)} 전후가 가장 유리합니다.`:'오늘 남은 추천 시간대가 없습니다.';$('scoreRing').style.setProperty('--score',todayScore??0);}
function endLabel(block){const d=new Date(`${block.end}:00+09:00`);d.setHours(d.getHours()+1);return String(d.getHours()).padStart(2,'0')+':00';}
function renderBest(best){const medals=['🥇','🥈','🥉'];$('bestTimes').innerHTML=best.length?best.map((b,i)=>`<li><span class="medal">${medals[i]}</span><span><strong>${timeOnly(b.start)}–${endLabel(b)}</strong><small>${b.duration}시간 추천 구간</small></span><span class="point">${b.score}점</span></li>`).join(''):'<li>추천 시간대 정보가 없습니다.</li>';}

function renderCurrent(c,w){const overall=scoreCondition(c.score);$('currentWeatherCard').dataset.condition=overall.key;$('currentWeatherCondition').className=`score-condition-badge condition-${overall.key}`;$('currentWeatherCondition').textContent=`${c.score}점 · ${overall.label}`;$('weatherIcon').textContent=weatherSymbol(c.weather_code);const items=[['temperature_2m','기온',formatValue(c.temperature_2m,'°C',1),c.temperature_2m],['apparent_temperature','체감',formatValue(c.apparent_temperature,'°C',1),c.apparent_temperature],['relative_humidity_2m','습도',formatValue(c.relative_humidity_2m,'%'),c.relative_humidity_2m],['dew_point_2m','이슬점',formatValue(c.dew_point_2m,'°C',1),c.dew_point_2m],['precipitation_probability','강수확률',formatValue(c.precipitation_probability,'%'),c.precipitation_probability],['precipitation','강수량',formatValue(c.precipitation,' mm',1),c.precipitation],['wind_speed_10m','바람',formatValue(c.wind_speed_10m,' km/h',1),c.wind_speed_10m],['wind_gusts_10m','돌풍',formatValue(c.wind_gusts_10m,' km/h',1),c.wind_gusts_10m],['pm2_5','PM2.5',formatValue(c.pm2_5,' μg/m³',1),c.pm2_5],['pm10','PM10',formatValue(c.pm10,' μg/m³',1),c.pm10],['air_quality_index','통합대기지수',formatValue(c.air_quality_index,''),c.air_quality_index],['uv_index','UV',formatValue(c.uv_index,'',1),c.uv_index]];$('weatherMetrics').innerHTML=items.map(([key,label,value,raw])=>{const condition=conditionFor(key,raw);return`<div class="metric condition-${condition.key}"><span>${label}</span><strong>${value}</strong><em>${condition.label}</em></div>`;}).join('');const sr=w.daily.sunrise[0],ss=w.daily.sunset[0];$('sunrise').textContent=timeOnly(sr);$('sunset').textContent=timeOnly(ss);const now=w.current.time;if(now<ss){const mins=Math.max(0,Math.round((new Date(`${ss}:00+09:00`)-new Date(`${now}:00+09:00`))/60000));$('sunStatus').textContent=`일몰까지 ${Math.floor(mins/60)}시간 ${mins%60}분 · 어두워지기 전 안전 장비를 확인하세요.`;}else $('sunStatus').textContent='Night Run · 밝은 색 복장과 반사 장비를 권장합니다.';}

function currentSeoulHour(){return new Date().toLocaleString('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).replace(' ','T')+':00';}
function renderHourly(){const compact=matchMedia('(max-width:700px)').matches;const allRows=state.hourlyDay===0?state.computed.todayRows:state.computed.tomorrowRows;const nowHour=currentSeoulHour();state.hourlyKey=nowHour;const rows=compact&&state.hourlyDay===0&&dateOnly(nowHour)===state.computed.today?allRows.filter(r=>r.time>=nowHour):allRows;renderHourlyChart($('hourlyChart'),rows,renderHourlyDetail,{compact});$('hourlyTextAlternative').textContent=rows.map(r=>`${timeOnly(r.time)} ${r.score}점`).join(', ');if(rows.length)renderHourlyDetail(rows[0]);else $('hourlyDetail').innerHTML=`<p class="muted">${state.hourlyDay===0?'오늘 남은 시간대':'선택한 날짜'}의 기상청 예보가 없습니다.</p>`;const nextButton=$('hourlyNextDay');nextButton.hidden=!(compact&&state.hourlyDay===0&&rows.length<=3);document.querySelectorAll('[data-hourly-day]').forEach((b,i)=>{b.classList.toggle('active',i===state.hourlyDay);b.setAttribute('aria-selected',String(i===state.hourlyDay));});}
function conditionFor(key,value){if(!Number.isFinite(value))return{key:'unknown',label:'정보 없음'};const rules={temperature_2m:[[5,18],[0,23],[-5,29]],apparent_temperature:[[5,18],[0,23],[-5,29]],relative_humidity_2m:[[30,60],[20,70],[10,82]],dew_point_2m:[[-30,10],[-30,15],[-30,20]],precipitation_probability:[[0,10],[0,30],[0,60]],precipitation:[[0,0],[0,.5],[0,2]],wind_speed_10m:[[0,12],[0,20],[0,30]],wind_gusts_10m:[[0,20],[0,30],[0,45]],pm2_5:[[0,15],[0,35],[0,75]],pm10:[[0,30],[0,50],[0,100]],air_quality_index:[[0,50],[0,100],[0,250]],uv_index:[[0,2],[0,5],[0,7]]};const bands=rules[key];if(!bands)return{key:'unknown',label:'참고'};if(value>=bands[0][0]&&value<=bands[0][1])return{key:'good',label:'좋음'};if(value>=bands[1][0]&&value<=bands[1][1])return{key:'normal',label:'보통'};if(value>=bands[2][0]&&value<=bands[2][1])return{key:'bad',label:'안좋음'};return{key:'very-bad',label:'아주 안좋음'};}
function scoreCondition(score){if(!Number.isFinite(score))return{key:'unknown',label:'정보 없음'};if(score>=90)return{key:'good',label:'좋음'};if(score>=75)return{key:'normal',label:'보통'};if(score>=60)return{key:'bad',label:'안좋음'};return{key:'very-bad',label:'아주 안좋음'};}
function average(rows,key){const values=rows.map(r=>r[key]).filter(Number.isFinite);return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;}
function scoreReason(rows){const basis=runnableRows(rows).sort((a,b)=>b.score-a.score).slice(0,4);if(!basis.length)return'기상청 단기예보 범위 밖이라 점수 근거를 계산할 수 없습니다.';const specs=[['temperature','apparent_temperature','체감','°C',1],['dewPoint','dew_point_2m','이슬점','°C',1],['humidity','relative_humidity_2m','습도','%',0],['rain','precipitation_probability','강수','%',0],['wind','wind_speed_10m','바람',' km/h',1],['airQuality','pm2_5','PM2.5',' μg/m³',1],['uv','uv_index','UV','',1]];const deductions=basis.map(r=>runningScoreDeductions(r));const factors=specs.map(([deductionKey,valueKey,label,unit,digits])=>{const value=average(basis,valueKey),deduction=deductions.reduce((sum,row)=>sum+(row[deductionKey]||0),0)/basis.length,condition=conditionFor(valueKey,value);return{label,value,deduction,condition,text:`${label} ${formatValue(value,unit,digits)}(-${deduction.toFixed(1)}점)`};}).filter(f=>Number.isFinite(f.value));const penalties=factors.filter(f=>f.deduction>=.1).sort((a,b)=>b.deduction-a.deduction).slice(0,3);const positives=factors.filter(f=>f.deduction<.1&&f.condition.key==='good').slice(0,2);const unfavorable=penalties.length?`주요 감점: ${penalties.map(f=>f.text).join(', ')}`:'감점 요인 없음';const airNote=basis.some(r=>r.air_quality_estimated)?' · 대기질은 에어코리아 예보 등급 환산값':' ';return`${unfavorable}${positives.length?` · 유리한 조건: ${positives.map(f=>`${f.label} ${formatValue(f.value,f.label==='바람'?' km/h':f.label==='강수'||f.label==='습도'?'%':f.label==='체감'||f.label==='이슬점'?'°C':f.label==='PM2.5'?' μg/m³':'',f.label==='습도'||f.label==='강수'?0:1)}`).join(', ')}`:''}${airNote}· 상위 4개 시간 평균`;}
function renderHourlyDetail(r){const overall=scoreCondition(r.score);const date=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(new Date(`${r.time}:00+09:00`));const metrics=[['temperature_2m','기온',formatValue(r.temperature_2m,'°C',1),r.temperature_2m],['apparent_temperature','체감',formatValue(r.apparent_temperature,'°C',1),r.apparent_temperature],['relative_humidity_2m','습도',formatValue(r.relative_humidity_2m,'%'),r.relative_humidity_2m],['dew_point_2m','이슬점',formatValue(r.dew_point_2m,'°C',1),r.dew_point_2m],['precipitation_probability','강수확률',formatValue(r.precipitation_probability,'%'),r.precipitation_probability],['wind_speed_10m','바람',formatValue(r.wind_speed_10m,' km/h',1),r.wind_speed_10m],['pm2_5',r.air_quality_estimated?'PM2.5 예보환산':'PM2.5',formatValue(r.pm2_5,' μg/m³',1),r.pm2_5],['air_quality_index','통합대기지수',formatValue(r.air_quality_index,''),r.air_quality_index]];$('hourlyDetail').innerHTML=`<div class="hourly-detail-heading"><strong>${date} ${timeOnly(r.time)} 상세 지표</strong><span class="hourly-score condition-${overall.key}">${r.score}점 · ${overall.label}</span></div><div class="condition-legend"><span class="condition-good">좋음</span><span class="condition-normal">보통</span><span class="condition-bad">안좋음</span><span class="condition-very-bad">아주 안좋음</span></div><div class="hourly-metrics">${metrics.map(([key,label,value,raw])=>{const c=conditionFor(key,raw);return`<span class="condition-${c.key}"><small>${label}</small><strong>${value}</strong><em>${c.label}</em></span>`;}).join('')}</div>`;}

function renderComparison(today,tomorrow,todayRows,tomorrowRows){const todayCondition=scoreCondition(today),tomorrowCondition=scoreCondition(tomorrow);$('compareToday').textContent=today??'--';$('compareTomorrow').textContent=tomorrow??'--';$('compareTodayGrade').textContent=todayCondition.label;$('compareTomorrowGrade').textContent=tomorrowCondition.label;$('compareTodayGrade').className=`condition-text-${todayCondition.key}`;$('compareTomorrowGrade').className=`condition-text-${tomorrowCondition.key}`;$('compareTodayReason').textContent=scoreReason(todayRows);$('compareTomorrowReason').textContent=scoreReason(tomorrowRows);let msg=Number.isFinite(today)&&Number.isFinite(tomorrow)?'오늘과 내일의 조건이 비슷합니다.':'비교할 예보가 충분하지 않습니다.';if(Number.isFinite(today)&&Number.isFinite(tomorrow)){if(tomorrow>today+3)msg='내일이 오늘보다 러닝하기 좋은 조건입니다.';else if(today>tomorrow+3)msg='오늘이 내일보다 러닝하기 좋은 조건입니다.';}const remainingToday=todayRows.filter(r=>r.time>=state.data.weather.current.time);const tb=findBestRunningTimes(remainingToday,1)[0],mb=findBestRunningTimes(tomorrowRows,1)[0];const candidates=[tb&&{label:'오늘',...tb},mb&&{label:'내일',...mb}].filter(Boolean).sort((a,b)=>b.score-a.score);if(candidates[0])msg+=` 앞으로는 ${candidates[0].label} ${timeOnly(candidates[0].start)} 전후가 가장 좋습니다.`;$('comparisonMessage').textContent=msg;}
function renderCoach(c,best){$('coachMessage').textContent=coachMessage(c,best);$('alerts').innerHTML=environmentAlerts(c).map(a=>`<span class="alert-chip">${a}</span>`).join('');}

function renderWeekly(w,hourly){const scores=w.daily.time.map(date=>dailyScore(rowsForDate(hourly,date))),finite=scores.filter(Number.isFinite),max=finite.length?Math.max(...finite):null;$('weeklyCards').innerHTML=w.daily.time.map((date,i)=>{const score=scores[i],available=Number.isFinite(score),condition=scoreCondition(score);return`<button class="day-card ${i===0?'active':''} ${available?'':'unavailable'}" data-day-index="${i}" aria-label="${monthDay(date)} ${available?`${score}점 ${condition.label}`:'예보 준비 중'}"><span>${i===0?'오늘':weekday(date)}</span><small>${monthDay(date)}</small><div class="day-icon">${weatherSymbol(w.daily.weather_code[i])}</div><strong>${score??'--'}</strong><small class="day-condition condition-${condition.key}">${available?condition.label:'예보 준비 중'}</small>${available&&score===max?'<small class="best-badge">BEST DAY</small>':''}</button>`;}).join('');document.querySelectorAll('.day-card').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.day-card').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderSelectedDay(Number(btn.dataset.dayIndex),w,hourly,scores);}));renderSelectedDay(0,w,hourly,scores);}
function renderSelectedDay(i,w,hourly,scores){const date=w.daily.time[i],allRows=rowsForDate(hourly,date),available=allRows.length>0;let recommendationRows=allRows;if(i===0)recommendationRows=recommendationRows.filter(r=>r.time>=w.current.time);const best=findBestRunningTimes(recommendationRows,1)[0],condition=scoreCondition(scores[i]);if(!available){$('selectedDayDetail').innerHTML=`<div class="selected-day-summary"><strong>${monthDay(date)} (${weekday(date)}) · 예보 준비 중</strong></div><p class="score-reason">현재 승인된 기상청 단기예보 범위 밖입니다. 중기예보 API를 연결하기 전까지 점수와 추천 시간을 만들지 않습니다.</p>`;return;}$('selectedDayDetail').innerHTML=`<div class="selected-day-summary"><strong>${monthDay(date)} (${weekday(date)}) · ${scores[i]??'--'}점 · ${condition.label}</strong><span>기온 ${formatValue(w.daily.temperature_2m_min[i],'°',0)}–${formatValue(w.daily.temperature_2m_max[i],'°C',0)}</span><span>강수확률 ${formatValue(w.daily.precipitation_probability_max[i],'%')}</span><span>최대 UV ${formatValue(w.daily.uv_index_max[i],'',1)}</span><span>추천 시간 ${best?`${timeOnly(best.start)}–${endLabel(best)}`:i===0?'오늘 남은 추천 시간 없음':'추천 시간 없음'}</span></div><p class="score-reason">${scoreReason(allRows)}</p>`;}
function renderWorkouts(c){const scores=workoutScores(c);$('workoutScores').innerHTML=Object.entries(scores).map(([name,score])=>{const condition=scoreCondition(score);return`<div class="workout-row workout-condition-${condition.key}"><span>${name}</span><div class="bar"><i style="width:${score}%"></i></div><strong>${score}</strong></div>`;}).join('');}
function renderGear(c){$('gearAdvice').innerHTML=Object.entries(gearAdvice(c)).map(([k,v])=>`<div class="gear-item"><span>${k}</span><strong>${v}</strong></div>`).join('');}

function calculatorTemplate(){const html=state.calcMode==='pace'?`<div class="field"><label for="paceInput">페이스 (분:초/km)</label><input id="paceInput" value="5:00" inputmode="numeric"></div>`:`<div class="field"><label for="speedInput">속도 (km/h)</label><input id="speedInput" type="number" min="0.1" step="0.1" value="12"></div>`;$('calculatorInputs').innerHTML=html;$('calculatorInputs').querySelectorAll('input').forEach(el=>el.addEventListener('input',calculate));calculate();}
function calculate(){const data=state.calcMode==='pace'?fromPace(parseClock($('paceInput')?.value)):fromSpeed(Number($('speedInput')?.value));if(!data||data.paceSeconds<120||data.paceSeconds>1800){$('calculatorError').textContent='올바른 값을 입력해 주세요. 페이스는 2:00–30:00/km 범위에서 계산합니다.';$('resultPace').textContent='--:--/km';$('resultSpeed').textContent='-- km/h';$('splitResults').innerHTML='';return;}$('calculatorError').textContent='';$('resultPace').textContent=renderPace(data.paceSeconds);$('resultSpeed').textContent=`${round(data.speed,1)} km/h`;$('splitResults').innerHTML=Object.entries(data.splits).map(([n,s])=>`<div class="split-item"><span>${n}</span><strong>${secondsToClock(s)}</strong></div>`).join('');}
function renderPaceTable(){const {startSeconds,endSeconds,stepSeconds}=APP_CONFIG.paceTable;$('paceTableBody').innerHTML=paceTableRows(startSeconds,endSeconds,stepSeconds).map(r=>`<tr><td>${renderPace(r.pace)}</td><td>${round(r.speed,1)}</td><td>${secondsToClock(r.splits['5K'])}</td><td>${secondsToClock(r.splits['10K'])}</td><td>${secondsToClock(r.splits.Half)}</td><td>${secondsToClock(r.splits.Marathon)}</td></tr>`).join('');}

function initLocationMap(){
  if(state.map||!window.kakao?.maps)return;
  const center=new kakao.maps.LatLng(state.location.latitude,state.location.longitude);
  state.map=new kakao.maps.Map($('locationMap'),{center,level:5});
  state.marker=new kakao.maps.Marker({position:center,map:state.map});
}
function showLocationOnMap(loc){
  initLocationMap();if(!state.map)return;
  const position=new kakao.maps.LatLng(loc.latitude,loc.longitude);
  state.map.relayout();state.map.setCenter(position);state.map.setLevel(4);state.marker.setPosition(position);
}
function previewLocation(loc,button){
  state.selectedLocation=loc;showLocationOnMap(loc);$('locationConfirm').hidden=false;
  $('locationResults').querySelectorAll('.location-result').forEach(item=>item.classList.toggle('selected',item===button));
  $('locationError').textContent=`${loc.address||loc.name} 위치를 확인한 뒤 사용 버튼을 눌러주세요.`;
}
function chooseLocation(loc){state.location=loc;state.selectedLocation=null;setStored('location',loc);$('locationConfirm').hidden=true;$('locationDialog').close();loadData(true);}
function locate(){if(!navigator.geolocation){$('locationError').textContent='이 브라우저는 위치 기능을 지원하지 않습니다.';return;}$('locationError').textContent='현재 위치와 주소를 확인하고 있습니다…';navigator.geolocation.getCurrentPosition(async pos=>{const latitude=round(pos.coords.latitude,6),longitude=round(pos.coords.longitude,6);try{chooseLocation(await reverseGeocode(latitude,longitude));}catch{chooseLocation({name:'현재 위치',address:'현재 위치',region1:'',region2:'',latitude,longitude});}},()=>{$('locationError').textContent='위치 권한이 거부되었거나 위치를 확인할 수 없습니다. 지역 검색을 이용해 주세요.';},{timeout:15000,maximumAge:300000,enableHighAccuracy:true});}
async function search(){const q=$('locationSearch').value.trim();if(q.length<2){$('locationError').textContent='주소나 장소명을 두 글자 이상 입력해 주세요.';return;}try{$('locationError').textContent='카카오에서 검색 중…';state.selectedLocation=null;$('locationConfirm').hidden=true;const results=await searchLocations(q);$('locationError').textContent=results.length?'검색 결과를 선택하면 지도에서 위치를 확인할 수 있습니다.':'검색 결과가 없습니다.';$('locationResults').innerHTML=results.map((r,i)=>`<button type="button" class="location-result" data-index="${i}" role="option"><strong>${escapeHtml(r.name)}</strong><small>${escapeHtml([r.category,r.roadAddress||r.address].filter(Boolean).join(' · '))}</small></button>`).join('');$('locationResults').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const r=results[Number(b.dataset.index)];previewLocation({name:r.name,address:r.address,roadAddress:r.roadAddress,region1:r.region1,region2:r.region2,region3:r.region3,latitude:r.latitude,longitude:r.longitude},b);}));if(results[0])previewLocation(results[0],$('locationResults').querySelector('button'));}catch(e){$('locationError').textContent=e.message;}}

$('locationButton').addEventListener('click',()=>{$('locationDialog').showModal();setTimeout(()=>{initLocationMap();state.map?.relayout();showLocationOnMap(state.location);$('locationSearch').focus();},0);});$('locationConfirm').addEventListener('click',()=>{if(state.selectedLocation)chooseLocation(state.selectedLocation);});$('useMyLocation').addEventListener('click',locate);$('searchLocation').addEventListener('click',search);$('locationSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search();}});$('refreshButton').addEventListener('click',()=>loadData(true));$('themeButton').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));document.querySelectorAll('[data-hourly-day]').forEach((b,i)=>b.addEventListener('click',()=>{state.hourlyDay=i;renderHourly();}));$('hourlyNextDay').addEventListener('click',()=>{state.hourlyDay=1;renderHourly();});document.querySelectorAll('[data-calc-mode]').forEach(b=>b.addEventListener('click',()=>{state.calcMode=b.dataset.calcMode;document.querySelectorAll('[data-calc-mode]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b);});calculatorTemplate();}));addEventListener('online',()=>{$('offlineBanner').hidden=true;loadData();});addEventListener('offline',()=>{$('offlineBanner').hidden=false;});

calculatorTemplate();renderPaceTable();loadData();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
