import { APP_CONFIG } from './running-score-config.js';
import { fetchWeather, searchLocations } from './weather.js';
import { fetchAirQuality } from './air-quality.js';
import { getStored, setStored, getCache, setCache } from './storage.js';
import { currentConditions, dailyScore, findBestRunningTimes, getGrade, mergeHourly, rowsForDate, workoutScores } from './running-score.js';
import { coachMessage, environmentAlerts, gearAdvice, runNowMessage } from './running-coach.js';
import { fromGoal, fromPace, fromSpeed, paceTableRows, renderPace } from './pace-calculator.js';
import { renderHourlyChart } from './charts.js';
import { dateOnly, escapeHtml, formatValue, monthDay, parseClock, round, secondsToClock, timeOnly, weatherSymbol, weekday } from './utils.js';

const $ = id => document.getElementById(id);
const state = { location:getStored('location',APP_CONFIG.defaultLocation), data:null, hourlyDay:0, calcMode:'goal', controller:null };

function setTheme(theme){document.documentElement.dataset.theme=theme;setStored('theme',theme);$('themeButton').setAttribute('aria-label',theme==='dark'?'라이트 모드 전환':'다크 모드 전환');}
setTheme(getStored('theme',matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));

function setLoading(isLoading){$('refreshButton').disabled=isLoading;$('refreshButton').textContent=isLoading?'…':'↻';}
function showError(message){$('errorBanner').textContent=message;$('errorBanner').hidden=!message;}
function nowSeoul(){return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());}
function updateClock(){$('headerClock').textContent=nowSeoul();}
updateClock();setInterval(updateClock,1000);

async function loadData(force=false){
  state.controller?.abort();state.controller=new AbortController();setLoading(true);showError('');$('headerLocation').textContent=state.location.name;
  const cached=getCache(state.location);const fresh=cached && Date.now()-cached.savedAt<APP_CONFIG.cacheMinutes*60000;
  if(!force && fresh){state.data={...cached.payload,savedAt:cached.savedAt,fromCache:true};render();setLoading(false);return;}
  try{
    const [weatherResult,airResult]=await Promise.allSettled([fetchWeather(state.location,state.controller.signal),fetchAirQuality(state.location,state.controller.signal)]);
    if(weatherResult.status==='rejected') throw weatherResult.reason;
    const payload={weather:weatherResult.value,air:airResult.status==='fulfilled'?airResult.value:null,airError:airResult.status==='rejected'};
    setCache(state.location,payload);state.data={...payload,savedAt:Date.now(),fromCache:false};render();
    if(payload.airError) showError('날씨는 정상 표시 중이지만 대기질 데이터를 가져오지 못했습니다. 대기질 항목은 제외됩니다.');
  }catch(error){
    if(error.name==='AbortError')return;
    if(cached){state.data={...cached.payload,savedAt:cached.savedAt,fromCache:true};render();showError('새 데이터를 가져오지 못해 마지막 저장 데이터를 표시합니다.');}
    else showError(`날씨 데이터를 가져오지 못했습니다. 네트워크 연결을 확인해 주세요. (${error.message})`);
  }finally{setLoading(false);}
}

function render(){
  const {weather,air}=state.data;const hourly=mergeHourly(weather,air);const current=currentConditions(weather,hourly);const today=dateOnly(weather.current.time);const todayRows=rowsForDate(hourly,today);const tomorrow=weather.daily.time[1];const tomorrowRows=rowsForDate(hourly,tomorrow);const best=findBestRunningTimes(todayRows);const futureBest=findBestRunningTimes(todayRows.filter(row=>row.time>=weather.current.time),1)[0];const todayScore=dailyScore(todayRows);const tomorrowScore=dailyScore(tomorrowRows);
  state.computed={hourly,current,today,todayRows,tomorrowRows,best,todayScore,tomorrowScore};
  renderHero(current,best,todayScore,futureBest);renderCurrent(current,weather);renderBest(best);renderHourly();renderComparison(todayScore,tomorrowScore,todayRows,tomorrowRows);renderCoach(current,futureBest);renderWeekly(weather,hourly);renderWorkouts(current);renderGear(current);
  $('updatedAt').textContent=`업데이트 ${new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit'}).format(new Date(state.data.savedAt))}${state.data.fromCache?' · 저장 데이터':''}`;
  $('offlineBanner').hidden=navigator.onLine;
}

function renderHero(c,best,todayScore,futureBest){const grade=getGrade(c.score);$('currentScore').classList.remove('skeleton-text');$('currentScore').textContent=c.score;$('currentGrade').textContent=grade.label;$('currentGrade').dataset.grade=grade.key;$('runNowMessage').textContent=runNowMessage(c,futureBest);$('heroTemp').textContent=formatValue(c.temperature_2m,'°C',1);$('heroFeels').textContent=formatValue(c.apparent_temperature,'°C',1);$('heroHumidity').textContent=formatValue(c.relative_humidity_2m,'%',0);$('heroDew').textContent=formatValue(c.dew_point_2m,'°C',1);$('todayBestScore').textContent=best[0]?`${best[0].score}점`:'--점';$('todayBestTime').textContent=best[0]?`BEST TIME ${timeOnly(best[0].start)}–${endLabel(best[0])}`:'BEST TIME --:--';$('todayScore').textContent=todayScore??'--';$('todayGrade').textContent=getGrade(todayScore??0).label;$('todaySummary').textContent=best[0]?`${timeOnly(best[0].start)} 전후가 오늘 가장 유리합니다.`:'추천 가능한 시간대가 없습니다.';$('scoreRing').style.setProperty('--score',todayScore??0);}
function endLabel(block){const d=new Date(`${block.end}:00+09:00`);d.setHours(d.getHours()+1);return String(d.getHours()).padStart(2,'0')+':00';}
function renderBest(best){const medals=['🥇','🥈','🥉'];$('bestTimes').innerHTML=best.length?best.map((b,i)=>`<li><span class="medal">${medals[i]}</span><span><strong>${timeOnly(b.start)}–${endLabel(b)}</strong><small>${b.duration}시간 추천 구간</small></span><span class="point">${b.score}점</span></li>`).join(''):'<li>추천 시간대 정보가 없습니다.</li>';}

function renderCurrent(c,w){$('weatherIcon').textContent=weatherSymbol(c.weather_code);const items=[['기온',formatValue(c.temperature_2m,'°C',1)],['체감',formatValue(c.apparent_temperature,'°C',1)],['습도',formatValue(c.relative_humidity_2m,'%')],['이슬점',formatValue(c.dew_point_2m,'°C',1)],['강수확률',formatValue(c.precipitation_probability,'%')],['강수량',formatValue(c.precipitation,' mm',1)],['바람',formatValue(c.wind_speed_10m,' km/h',1)],['돌풍',formatValue(c.wind_gusts_10m,' km/h',1)],['PM2.5',formatValue(c.pm2_5,' μg/m³',1)],['PM10',formatValue(c.pm10,' μg/m³',1)],['AQI',formatValue(c.european_aqi,'')],['UV',formatValue(c.uv_index,'',1)]];$('weatherMetrics').innerHTML=items.map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${v}</strong></div>`).join('');const sr=w.daily.sunrise[0],ss=w.daily.sunset[0];$('sunrise').textContent=timeOnly(sr);$('sunset').textContent=timeOnly(ss);const now=w.current.time;if(now<ss){const mins=Math.max(0,Math.round((new Date(`${ss}:00+09:00`)-new Date(`${now}:00+09:00`))/60000));$('sunStatus').textContent=`일몰까지 ${Math.floor(mins/60)}시간 ${mins%60}분 · 어두워지기 전 안전 장비를 확인하세요.`;}else $('sunStatus').textContent='Night Run · 밝은 색 복장과 반사 장비를 권장합니다.';}

function renderHourly(){const rows=state.hourlyDay===0?state.computed.todayRows:state.computed.tomorrowRows;renderHourlyChart($('hourlyChart'),rows,renderHourlyDetail);$('hourlyTextAlternative').textContent=rows.map(r=>`${timeOnly(r.time)} ${r.score}점`).join(', ');if(rows.length)renderHourlyDetail(rows.find(r=>r.time>=state.data.weather.current.time)||rows[0]);document.querySelectorAll('[data-hourly-day]').forEach((b,i)=>b.classList.toggle('active',i===state.hourlyDay));}
function renderHourlyDetail(r){const grade=getGrade(r.score);const date=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(new Date(`${r.time}:00+09:00`));const metrics=[['기온',formatValue(r.temperature_2m,'°C',1)],['체감',formatValue(r.apparent_temperature,'°C',1)],['습도',formatValue(r.relative_humidity_2m,'%')],['이슬점',formatValue(r.dew_point_2m,'°C',1)],['강수확률',formatValue(r.precipitation_probability,'%')],['바람',formatValue(r.wind_speed_10m,' km/h',1)],['PM2.5',formatValue(r.pm2_5,' μg/m³',1)],['AQI',formatValue(r.european_aqi,'')]];$('hourlyDetail').innerHTML=`<div class="hourly-detail-heading"><strong>${date} ${timeOnly(r.time)} 상세 지표</strong><span class="hourly-score grade-${grade.key}">${r.score}점 · ${grade.label}</span></div><div class="hourly-metrics">${metrics.map(([k,v])=>`<span><small>${k}</small><strong>${v}</strong></span>`).join('')}</div>`;}

function renderComparison(today,tomorrow,todayRows,tomorrowRows){$('compareToday').textContent=today??'--';$('compareTomorrow').textContent=tomorrow??'--';$('compareTodayGrade').textContent=getGrade(today??0).label;$('compareTomorrowGrade').textContent=getGrade(tomorrow??0).label;let msg='오늘과 내일의 조건이 비슷합니다.';if(tomorrow>today+3)msg='내일이 오늘보다 러닝하기 좋은 조건입니다.';else if(today>tomorrow+3)msg='오늘이 내일보다 러닝하기 좋은 조건입니다.';const tb=findBestRunningTimes(todayRows,1)[0],mb=findBestRunningTimes(tomorrowRows,1)[0];if(tb&&mb&&Math.max(tb.score,mb.score)>=90){const winner=tb.score>=mb.score?'오늘':'내일';const b=tb.score>=mb.score?tb:mb;msg+=` ${winner} ${timeOnly(b.start)} 전후가 향후 48시간 중 가장 좋습니다.`;}$('comparisonMessage').textContent=msg;}
function renderCoach(c,best){$('coachMessage').textContent=coachMessage(c,best);$('alerts').innerHTML=environmentAlerts(c).map(a=>`<span class="alert-chip">${a}</span>`).join('');}

function renderWeekly(w,hourly){const scores=w.daily.time.map(date=>dailyScore(rowsForDate(hourly,date)));const max=Math.max(...scores.filter(Number.isFinite));$('weeklyCards').innerHTML=w.daily.time.map((date,i)=>`<button class="day-card ${i===0?'active':''}" data-day-index="${i}" aria-label="${monthDay(date)} ${scores[i]}점"><span>${i===0?'오늘':weekday(date)}</span><small>${monthDay(date)}</small><div class="day-icon">${weatherSymbol(w.daily.weather_code[i])}</div><strong>${scores[i]??'--'}</strong>${scores[i]===max?'<small class="best-badge">BEST DAY</small>':''}</button>`).join('');document.querySelectorAll('.day-card').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.day-card').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderSelectedDay(Number(btn.dataset.dayIndex),w,hourly,scores);}));renderSelectedDay(0,w,hourly,scores);}
function renderSelectedDay(i,w,hourly,scores){const date=w.daily.time[i],rows=rowsForDate(hourly,date),best=findBestRunningTimes(rows,1)[0];$('selectedDayDetail').innerHTML=`<strong>${monthDay(date)} (${weekday(date)}) · ${scores[i]??'--'}점</strong><span>기온 ${formatValue(w.daily.temperature_2m_min[i],'°',0)}–${formatValue(w.daily.temperature_2m_max[i],'°C',0)}</span><span>강수확률 ${formatValue(w.daily.precipitation_probability_max[i],'%')}</span><span>최대 UV ${formatValue(w.daily.uv_index_max[i],'',1)}</span><span>추천 시간 ${best?`${timeOnly(best.start)}–${endLabel(best)}`:'정보 없음'}</span>`;}
function renderWorkouts(c){const scores=workoutScores(c);$('workoutScores').innerHTML=Object.entries(scores).map(([name,score])=>`<div class="workout-row"><span>${name}</span><div class="bar"><i style="width:${score}%"></i></div><strong>${score}</strong></div>`).join('');}
function renderGear(c){$('gearAdvice').innerHTML=Object.entries(gearAdvice(c)).map(([k,v])=>`<div class="gear-item"><span>${k}</span><strong>${v}</strong></div>`).join('');}

function calculatorTemplate(){const d=APP_CONFIG.distances;let html='';if(state.calcMode==='goal')html=`<div class="field"><label for="goalDistance">거리</label><select id="goalDistance">${Object.entries(d).map(([n,k])=>`<option value="${k}" ${n==='10K'?'selected':''}>${n}</option>`).join('')}<option value="custom">직접 입력</option></select></div><div class="field" id="customDistanceWrap" hidden><label for="customDistance">거리(km)</label><input id="customDistance" type="number" min="0.1" step="0.1" value="15"></div><div class="field"><label for="goalTime">목표 기록 (시:분:초)</label><input id="goalTime" value="00:50:00" inputmode="numeric"></div>`;if(state.calcMode==='pace')html=`<div class="field"><label for="paceInput">페이스 (분:초/km)</label><input id="paceInput" value="5:00" inputmode="numeric"></div>`;if(state.calcMode==='speed')html=`<div class="field"><label for="speedInput">속도 (km/h)</label><input id="speedInput" type="number" min="0.1" step="0.1" value="12"></div>`;$('calculatorInputs').innerHTML=html;$('calculatorInputs').querySelectorAll('input,select').forEach(el=>el.addEventListener('input',calculate));$('goalDistance')?.addEventListener('change',e=>{$('customDistanceWrap').hidden=e.target.value!=='custom';calculate();});calculate();}
function calculate(){let data=null;if(state.calcMode==='goal'){const sel=$('goalDistance');const distance=sel?.value==='custom'?Number($('customDistance')?.value):Number(sel?.value);data=fromGoal(distance,parseClock($('goalTime')?.value));}else if(state.calcMode==='pace')data=fromPace(parseClock($('paceInput')?.value));else data=fromSpeed(Number($('speedInput')?.value));if(!data||data.paceSeconds<120||data.paceSeconds>1800){$('calculatorError').textContent='올바른 값을 입력해 주세요. 페이스는 2:00–30:00/km 범위에서 계산합니다.';$('resultPace').textContent='--:--/km';$('resultSpeed').textContent='-- km/h';$('splitResults').innerHTML='';return;}$('calculatorError').textContent='';$('resultPace').textContent=renderPace(data.paceSeconds);$('resultSpeed').textContent=`${round(data.speed,1)} km/h`;$('splitResults').innerHTML=Object.entries(data.splits).map(([n,s])=>`<div class="split-item"><span>${n}</span><strong>${secondsToClock(s)}</strong></div>`).join('');}
function renderPaceTable(){const parseTime=v=>{const [h,m,s]=v.split(':').map(Number);return h*3600+m*60+s;};let start=parseTime($('paceStart').value),end=parseTime($('paceEnd').value);if(start>end)[start,end]=[end,start];$('paceTableBody').innerHTML=paceTableRows(start,end,10).map(r=>`<tr><td>${renderPace(r.pace)}</td><td>${round(r.speed,1)}</td><td>${secondsToClock(r.splits['5K'])}</td><td>${secondsToClock(r.splits['10K'])}</td><td>${secondsToClock(r.splits.Half)}</td><td>${secondsToClock(r.splits.Marathon)}</td></tr>`).join('');}

function chooseLocation(loc){state.location=loc;setStored('location',loc);$('locationDialog').close();loadData(true);}
function locate(){if(!navigator.geolocation){$('locationError').textContent='이 브라우저는 위치 기능을 지원하지 않습니다.';return;}$('locationError').textContent='현재 위치를 확인하고 있습니다…';navigator.geolocation.getCurrentPosition(pos=>{chooseLocation({name:'현재 위치',latitude:round(pos.coords.latitude,4),longitude:round(pos.coords.longitude,4)});},()=>{$('locationError').textContent='위치 권한이 거부되었거나 위치를 확인할 수 없습니다. 지역 검색을 이용해 주세요.';},{timeout:10000,enableHighAccuracy:false});}
async function search(){const q=$('locationSearch').value.trim();if(q.length<2){$('locationError').textContent='지역명을 두 글자 이상 입력해 주세요.';return;}try{$('locationError').textContent='검색 중…';const results=await searchLocations(q);$('locationError').textContent=results.length?'':'검색 결과가 없습니다.';$('locationResults').innerHTML=results.map((r,i)=>`<button type="button" class="location-result" data-index="${i}" role="option"><strong>${escapeHtml(r.name)}</strong><small>${escapeHtml([r.admin2,r.admin1,r.country].filter(Boolean).join(', '))}</small></button>`).join('');$('locationResults').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const r=results[Number(b.dataset.index)];chooseLocation({name:[r.name,r.admin2].filter(Boolean).join(' '),latitude:r.latitude,longitude:r.longitude});}));}catch(e){$('locationError').textContent=e.message;}}

$('locationButton').addEventListener('click',()=>{$('locationDialog').showModal();$('locationSearch').focus();});$('useMyLocation').addEventListener('click',locate);$('searchLocation').addEventListener('click',search);$('locationSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search();}});$('refreshButton').addEventListener('click',()=>loadData(true));$('themeButton').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));document.querySelectorAll('[data-hourly-day]').forEach((b,i)=>b.addEventListener('click',()=>{state.hourlyDay=i;renderHourly();}));document.querySelectorAll('[data-calc-mode]').forEach(b=>b.addEventListener('click',()=>{state.calcMode=b.dataset.calcMode;document.querySelectorAll('[data-calc-mode]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b);});calculatorTemplate();}));$('paceStart').addEventListener('input',renderPaceTable);$('paceEnd').addEventListener('input',renderPaceTable);addEventListener('online',()=>{$('offlineBanner').hidden=true;loadData();});addEventListener('offline',()=>{$('offlineBanner').hidden=false;});

calculatorTemplate();renderPaceTable();loadData();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
